name: AI Front Matter Generator

on:
  pull_request:
    paths: 
      - 'content/posts/**/*.md'
    types: [opened, synchronize]

jobs:
  generate-frontmatter:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: content/posts/**/*.md
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install openai pyyaml python-frontmatter
          
      - name: Generate AI suggestions
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python .github/scripts/generate_frontmatter.py "${{ steps.changed-files.outputs.all_changed_files }}"
          
      - name: Comment PR with suggestions
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            if (fs.existsSync('ai-suggestions.md')) {
              const suggestions = fs.readFileSync('ai-suggestions.md', 'utf8');
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: suggestions
              });
            }